version: '3.4'

services:
  OrderApi:
    image: ${DOCKER_REGISTRY-}order-api
    build:
      context: .
      dockerfile: src/Services/Order/Api/Dockerfile
    container_name: order-api
    depends_on:
      - OrderDb

  InventoryApi:
    image: ${DOCKER_REGISTRY-}inventory-api
    build:
      context: .
      dockerfile: src/Services/Inventory/Api/Dockerfile
    container_name: inventory-api
    depends_on:
      - InventoryDb

  PaymentApi:
    image: ${DOCKER_REGISTRY-}payment-api
    build:
      context: .
      dockerfile: src/Services/Payment/Api/Dockerfile
    container_name: payment-api
    depends_on:
      - PaymentDb

  OrderDb:
    image: postgres
    container_name: order-db

  InventoryDb:
    image: postgres
    container_name: inventory-db

  PaymentDb:
    image: postgres
    container_name: payment-db


